container:
  cpu: 4
  memory: 8G

pipe:
  name: site-validation
  steps:
    - build_script: mvn clean site -Pno-validations

task:
  name: verify
  container:
    image: maven:latest
  test_script: mvn clean verify
